# .github/workflows/chromatic.yml

name: 'Chromatic' # 定义工作流名称

# 触发条件，这里是代码推送到任何分支时触发
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.eslintrc.json'
      - '.prettierrc'
      - 'babel.config.js'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.eslintrc.json'
      - '.prettierrc'
      - 'babel.config.js'

jobs:
  chromatic: # 定义一个名为 chromatic 的 job
    name: Run Chromatic # job 的名称
    runs-on: ubuntu-latest # 指定运行环境为最新版本的 Ubuntu

    steps: # 定义 job 的多个步骤
      - name: Checkout code # 第一步：检出代码
        uses: actions/checkout@v4 # 使用 actions/checkout v4 版本
        with:
          fetch-depth: 0 # 完全检出所有提交记录

      - uses: actions/setup-node@v4 # 第二步：设置 Node.js 环境
        with:
          node-version: 20 # 指定 Node.js 版本为 20

      - name: Install dependencies # 第三步：安装依赖
        run: npm ci # 使用 npm ci 命令安装依赖，确保环境干净

      - name: Run Chromatic # 第四步：运行 Chromatic
        uses: chromaui/action@latest # 使用 chromaui/action 的最新版本
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} # 传递 Chromatic 项目令牌，确保在 GitHub 仓库的 Secrets 中配置了 CHROMATIC_PROJECT_TOKEN
